---
version: "2.1"
services:
  ticktick:
    build: . 
    image: ticktick-repeat
    container_name: ticktick
    networks:
        - lsio
    ports:
        - 5000:5000
    restart: unless-stopped

networks:
    lsio:
        external: true
